export const ROLES = {
    ADMIN: "ADMIN",
    BASE_COMMANDER: "BASE_COMMANDER",
    LOGISTICS_OFFICER: "LOGISTICS_OFFICER",
  };
  
  export const TRANSFER_STATUS = {
    DRAFT: "DRAFT",
    APPROVED: "APPROVED",
    DISPATCHED: "DISPATCHED",
    RECEIVED: "RECEIVED",
  };
  
  export const LEDGER_MOVE = {
    PURCHASE: "PURCHASE",
    TRANSFER_IN: "TRANSFER_IN",
    TRANSFER_OUT: "TRANSFER_OUT",
    ASSIGN: "ASSIGN",
    EXPEND: "EXPEND",
  };
  